### ISSUE TITLE
Problem/issues

### ISSUE THREAD

**Issue by JonathanNaik** [JonathanNaik/angular-primery-app#1]
ERROR ReferenceError: sessionStorage is not defined
    at authGuard (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:12975:3)
    at eval (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:2367:156)
    at Module.runInInjectionContext (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:5562:12)
    at eval (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:2367:111)
    at _Observable.eval [as _subscribe] (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:1640:15)
    at _Observable._trySubscribe (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:660:19)
    at eval (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:5085dules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:654:113)
    at errorContext (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:449:5)
    at _Observable.subscribe (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/depimery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:652:5)       
    at eval (eval at instantiateModule (file:///F:/My%20App/secondApp/angular-primery-app/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:5085dules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28), <anonymous>:1752:12)

**Comment by JonathanNaik** [comment]
issue is in session storage which i have used in>
src/app/guards/auth.guard.ts
